import { NodeConfig } from "./types";

export const roiNodeConfig: NodeConfig = {
  nodeName: "ROI",
  processorType: "roi",
  icon: "MdOutlineCrop",
  inputNames: ["input_url"],
  fields: [
    {
      name: "input_url",
      label: "Input (asset or stream)",
      type: "input",
      hasHandle: true,
      required: true,
      placeholder: "/asset/<image>.jpg or stream://<id>",
    },
    {
      name: "x",
      label: "X (0-1)",
      type: "numericfield",
      defaultValue: 0,
      min: 0,
      max: 1,
      step: 0.01,
      allowDecimal: true,
    },
    {
      name: "y",
      label: "Y (0-1)",
      type: "numericfield",
      defaultValue: 0,
      min: 0,
      max: 1,
      step: 0.01,
      allowDecimal: true,
    },
    {
      name: "w",
      label: "W (0-1)",
      type: "numericfield",
      defaultValue: 1,
      min: 0,
      max: 1,
      step: 0.01,
      allowDecimal: true,
    },
    {
      name: "h",
      label: "H (0-1)",
      type: "numericfield",
      defaultValue: 1,
      min: 0,
      max: 1,
      step: 0.01,
      allowDecimal: true,
    },
  ],
  outputType: "imageUrl",
  section: "tools",
  category: "processing",
  helpMessage: "Crop a region of interest from an image or stream",
};
